### ISSUE TITLE
Use bootstrap to setup skeleton of the website

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#1]
Hey Opencoders! 

Let's kickstart this amazing journey of opensource by adding yourself as a contributor to this repo.We're interested in helping you take the first step and can answer questions and help you out as you do.

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart: 

:thinking:  What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

**Comment by rishika8910** [comment]
can I work on this issue?

**Comment by Archies11** [comment]
Sure go ahead!
You should comment @opencodebot claim to claim the issue first.

**Comment by rishika8910** [comment]
@opencodebot claim

**Comment by CadencePrestissimo** [comment]
@opencodebot claim

**Comment by CadencePrestissimo** [comment]
@opencodebot claim
