### ISSUE TITLE
Design an apt logo for the website

### ISSUE THREAD

**Issue by palak2001** [opencodeiiita/Code-like-a-Girl#2]
This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
* Design a creative logo for this repo, and earn points! 

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🤔 Questions?
Leave a comment below!

**Comment by CadencePrestissimo** [comment]
@opencodebot claim

**Comment by CadencePrestissimo** [comment]
@opencodebot claim

**Comment by mendelevium28** [comment]
i would also like to work on this
