### ISSUE TITLE
Create a preloader for the website

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#28]
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Use the name of the repo or the logo or animation for a unique preloader.

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

**Comment by naina24** [comment]
May I work on this??

**Comment by CadencePrestissimo** [comment]
I want to work on this

**Comment by Archies11** [comment]
assigned to @iit2019004

**Comment by roshnidesigns** [comment]
claim

**Comment by Archies11** [comment]
@iit2019004 updates?

**Comment by Archies11** [comment]
unassigned due to inactivity.

**Comment by ananya-mohanty** [comment]
Claim

**Comment by Archies11** [comment]
@ananya-mohanty  you already have two issues to work on.
reassigned to @iit2019004

**Comment by naina24** [comment]
Ma`am,I have animated the logo which would work as a preloader. I am trying but I am unsuccessful to align the animated logo at the center.

**Comment by ananya-mohanty** [comment]
Claim

**Comment by Archies11** [comment]
> Ma`am,I have animated the logo which would work as a preloader. I am trying but I am unsuccessful to align the animated logo at the center.

Push the changes you have made and we can discuss your issues from there on.
