### ISSUE TITLE
Add an about section for the website

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#30]
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

**Comment by CadencePrestissimo** [comment]
i want to work on it

**Comment by Archies11** [comment]
Go ahead!

**Comment by Saggittarius-A** [comment]
i want to work on this project.
