### ISSUE TITLE
Add a gallery to the website

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#31]
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Add photos of she hacks'18, Opencode'18 and HINT'18
* Use bootstrap to either set up a slideshow of photos or a carousel or any other style of your choice.

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

**Comment by roshnidesigns** [comment]
claim

**Comment by Archies11** [comment]
assigned to @tinycosmos

**Comment by Archies11** [comment]
unassigned due to inactivity.

**Comment by ananya-mohanty** [comment]
Claim

**Comment by Archies11** [comment]
Assigned to @ananya-mohanty
