### ISSUE TITLE
Add a contributors section to the website

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#34]
Hey Opencoders! 

:thinking:  What you will need to know.
Basic HTML, CSS, Bootstrap

:clipboard:  Step by Step

* Read about basic HTML and bootstrap elements.[here is a tutorial ](https://www.w3schools.com/html/)
* Fork and then clone the repo.
* Edit the index.html file (create css files seperately if needed) and voila! 
* Add cards to display the names of the contributors and their github accounts. 

 :floppy_disk:  Commit your changes

 :twisted_rightwards_arrows:  Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.  

:thinking:  Questions?
Leave a comment below!

**Comment by CadencePrestissimo** [comment]
claim

**Comment by Archies11** [comment]
@pavikachaudhary you already have claimed two issues. Merge PRs for those first

**Comment by naina24** [comment]
claim

**Comment by roshnidesigns** [comment]
claim

**Comment by mendelevium28** [comment]
Claim

**Comment by Archies11** [comment]
Assigned to @iit2019004

**Comment by Archies11** [comment]
unassigned due to inactivity. this issue is up for grabs.

**Comment by ananya-mohanty** [comment]
Claim

**Comment by Archies11** [comment]
assigned to @ananya-mohanty
