### ISSUE TITLE
Fix the bootstrap links of the website 

### ISSUE THREAD

**Issue by Archies11** [opencodeiiita/Code-like-a-Girl#35]
The website currently does not render the bootstrap classes and features used. Fix the bootstrap links used to render a bootstrap website skeleton.

**Comment by Saggittarius-A** [comment]
claim

**Comment by Archies11** [comment]
Assigned to @iit2019017

**Comment by ananya-mohanty** [comment]
Claim

**Comment by Archies11** [comment]
@iit2019017 updates?

**Comment by Archies11** [comment]
unassigned due to inactivity.
